# back to language cpp to try to bypass osx node failure
---
language: node_js
node_js:
  - 7
cache:
  directories:
  - node_modules
before_script:
  - npm install -g gatsby-cli
# script needed to test, because defaults don't work on osx
script:
  - npm install
  - npm run format
  - gatsby build

notifications:
  slack: ab--space:clGeU06zSZvLRmHXGzKU4E1u